// ============================================================
// BIO Week 4–5 Term Matching — default content
// Term groups, slides, default definitions, default slide hints
// All values can be overridden by the teacher and saved to localStorage
// ============================================================

const SLIDES = [
    {id: 'simple_squamous_pavement', label: 'Simple Squamous (Pavement) — Mesentery'},
    {id: 'simple_cuboidal_pancreas', label: 'Simple Cuboidal — Pancreatic Duct'},
    {id: 'simple_columnar_jejunum', label: 'Simple Columnar — Jejunum'},
    {id: 'pseudostratified_trachea', label: 'Pseudostratified Columnar — Trachea'},
    {id: 'strat_squamous_keratinized', label: 'Keratinized Stratified Squamous — Thick Skin'},
    {id: 'strat_squamous_nonkeratinized', label: 'Non-keratinized Stratified Squamous — Esophagus'},
    {id: 'strat_cuboidal_esophagus', label: 'Stratified Cuboidal — Esophagus Gland Duct'},
    {id: 'transitional_bladder', label: 'Transitional — Bladder'},
    {id: 'areolar_mesentery', label: 'Areolar Loose CT — Mesentery'},
    {id: 'adipose_white', label: 'White Adipose — Mesentery'},
    {id: 'adipose_brown', label: 'Brown Adipose Tissue'},
    {id: 'reticular_spleen', label: 'Reticular CT — Spleen'},
    {id: 'dense_regular_tendon', label: 'Dense Regular CT — Tendon'},
    {id: 'dense_irregular_dermis', label: 'Dense Irregular CT — Dermis'},
    {id: 'mucous_ct_umbilical', label: "Mucous CT — Umbilical Cord (Wharton's Jelly)"},
    {id: 'mast_cells_toluidine', label: 'Mast Cells — Pancreas'},
    {id: 'hyaline_cartilage_trachea', label: 'Hyaline Cartilage — Trachea'},
    {id: 'elastic_cartilage_ear', label: 'Elastic Cartilage — External Ear'},
    {id: 'fibrocartilage_disc', label: 'Fibrocartilage — Intervertebral Disc'},
    {id: 'compact_bone_ground', label: 'Compact Bone — Ground Section'},
    {id: 'compact_spongy_bone', label: 'Compact + Spongy Bone'},
    {id: 'skeletal_long', label: 'Skeletal Muscle — Longitudinal'},
    {id: 'cardiac_intercalated', label: 'Cardiac Muscle — Intercalated Discs'},
    {id: 'smooth_muscle', label: 'Smooth Muscle'},
    {id: 'neuron_golgi', label: 'Multipolar Neurons — Golgi Stain (Brain)'},
    {id: 'peripheral_nerve', label: 'Peripheral Nerve — Long & Cross'},
    {id: 'dorsal_root_ganglion', label: 'Dorsal Root Ganglion'},
    {id: 'blood_smear', label: 'Peripheral Blood Smear'},
    // OpenStax A&P 2e diagrams (CC BY 4.0) — added to cover multi-term concepts
    {id: 'skin_layers', label: 'Layers of the Epidermis (OpenStax Fig 5.5)', type: 'jpg'},
    {id: 'cell_junctions', label: 'Cell Junctions (OpenStax Fig 4.5)', type: 'jpg'},
    {id: 'epithelium_structure', label: 'Cells of Epithelial Tissue (OpenStax Fig 4.8)', type: 'jpg'},
    {id: 'gland_secretion_modes', label: 'Modes of Glandular Secretion (OpenStax Fig 4.10)', type: 'jpg'},
    {id: 'tissue_membranes', label: 'Tissue Membranes (OpenStax Fig 4.4)', type: 'jpg'},
    {id: 'wound_healing', label: 'Tissue Healing (OpenStax Fig 4.21)', type: 'jpg'},
    {id: 'skin_full_cross_section', label: 'Layers of the Skin — Full Cross-Section (OpenStax Fig 5.2)', type: 'jpg'},
    {id: 'neuroglia_cns', label: 'Glial Cells of the CNS (OpenStax Fig 12.11)', type: 'jpg'},
    {id: 'neuroglia_pns', label: 'Glial Cells of the PNS (OpenStax Fig 12.12)', type: 'jpg'},
    {id: 'apoptosis_necrosis', label: 'Apoptosis vs Necrosis (Wikimedia, public domain)', type: 'png'},
    {id: 'inflammation_cascade', label: 'Inflammatory Response (OpenStax Fig 21.14)', type: 'jpg'}
];

const TERM_GROUPS = [
    {id: 'ch4_tissue_types', chapter: 4, title: 'Tissue Types & Muscle',
     terms: ['muscle tissue', 'cardiac muscle', 'skeletal muscle', 'smooth muscle', 'striation', 'nervous tissue']},
    {id: 'ch4_neural', chapter: 4, title: 'Nervous Tissue Cells',
     terms: ['neuron', 'neuroglia', 'astrocyte', 'oligodendrocyte', 'Schwann cell', 'myelin']},
    {id: 'ch4_ct_cells', chapter: 4, title: 'Connective Tissue Cells',
     terms: ['adipocytes', 'chondrocytes', 'fibroblast', 'fibrocyte', 'mesenchymal cell', 'myocyte', 'parenchyma']},
    {id: 'ch4_epithelium', chapter: 4, title: 'Epithelium Structure',
     terms: ['apical', 'basal lamina', 'basement membrane', 'lamina propria', 'reticular lamina']},
    {id: 'ch4_junctions', chapter: 4, title: 'Cell Junctions',
     terms: ['cell junction', 'anchoring junction', 'desmosome', 'hemidesmosomes', 'adherens', 'gap junction', 'tight junction']},
    {id: 'ch4_glands', chapter: 4, title: 'Glands & Secretion',
     terms: ['endocrine gland', 'exocrine gland', 'mucous gland', 'serous gland', 'goblet cell', 'apocrine secretion', 'merocrine secretion', 'holocrine secretion']},
    {id: 'ch4_membranes', chapter: 4, title: 'Tissue Membranes',
     terms: ['tissue membrane', 'epithelial membrane', 'connective tissue membrane', 'cutaneous membrane', 'mucous membrane', 'serous membrane', 'synovial membrane']},
    {id: 'ch4_response', chapter: 4, title: 'Tissue Response & Healing',
     terms: ['inflammation', 'histamine', 'vasodilation', 'clotting', 'wound contraction', 'primary union', 'secondary union', 'apoptosis', 'atrophy', 'necrosis']},
    {id: 'ch5_overview', chapter: 5, title: 'Skin Overview',
     terms: ['integumentary system', 'epidermis', 'dermis', 'hypodermis', 'papillary layer', 'reticular layer', 'dermal papilla', 'elastin fibers']},
    {id: 'ch5_strata', chapter: 5, title: 'Epidermal Strata',
     terms: ['stratum basale', 'stratum spinosum', 'stratum granulosum', 'stratum lucidum', 'stratum corneum']},
    {id: 'ch5_cells', chapter: 5, title: 'Skin Cells & Receptors',
     terms: ['basal cell', 'keratinocyte', 'melanocyte', 'Langerhans cell', 'Merkel cell', 'Meissner corpuscle', 'Pacinian corpuscle']},
    {id: 'ch5_proteins', chapter: 5, title: 'Skin Proteins & Pigments',
     terms: ['keratin', 'keratohyalin', 'eleiden', 'melanin', 'melanosome']}
];

// Definitions sourced from OpenStax Anatomy & Physiology 2e (CC BY 4.0), Chapters 4–5
const DEFAULT_DEFINITIONS = {
    // Chapter 4
    'muscle tissue': 'Excitable tissue composed of contractile fibers that shorten in response to stimulation, producing movement of the body or its internal contents.',
    'cardiac muscle': 'Striated, involuntary muscle made of short branched cells with a single central nucleus, found only in the heart wall pumping blood.',
    'skeletal muscle': 'Long, cylindrical, striated voluntary muscle fibers with many peripheral nuclei, attached to bones to produce conscious body movement and heat.',
    'smooth muscle': 'Short, spindle-shaped involuntary muscle fibers with one central nucleus and no striations, found in walls of hollow organs and vessels.',
    'striation': 'Alternating light and dark bands seen in skeletal and cardiac muscle, produced by the regular arrangement of actin and myosin filaments.',
    'myelin': 'Lipid-rich insulating sheath wrapped around axons by oligodendrocytes or Schwann cells that speeds the conduction of nerve impulses.',
    'nervous tissue': 'Excitable tissue made of neurons and neuroglia that propagates electrochemical impulses to sense, integrate, and respond to stimuli.',
    'apical': 'The exposed, free surface of an epithelial cell facing the lumen or external environment, opposite the basal surface.',
    'basal lamina': 'Thin glycoprotein-and-collagen layer secreted by epithelial cells that anchors the epithelium to underlying connective tissue.',
    'basement membrane': 'Composite extracellular layer formed where the epithelial basal lamina joins the connective-tissue reticular lamina, anchoring epithelium beneath it.',
    'lamina propria': 'Loose connective tissue layer of a mucous membrane that lies beneath and supports its overlying epithelium.',
    'reticular lamina': 'Layer of reticular fibers secreted by underlying connective tissue that joins the basal lamina to form the basement membrane.',
    'adipocytes': 'Connective tissue cells specialized to store lipid as a single large droplet, occurring in white or brown forms.',
    'astrocyte': 'Star-shaped neuroglial cell of the central nervous system that regulates ions, recycles neurotransmitters, and helps form the blood-brain barrier.',
    'chondrocytes': 'Mature cartilage cells that maintain the cartilage matrix while sitting individually within small fluid-filled spaces called lacunae.',
    'fibroblast': 'Most abundant cell of connective tissue proper, secreting collagen, elastic fibers, and ground substance of the extracellular matrix.',
    'fibrocyte': 'Less active mature form of a fibroblast that maintains, rather than produces, the fibers and matrix of connective tissue.',
    'mesenchymal cell': 'Multipotent adult stem cell of connective tissue that can differentiate into various cell types needed for growth and repair.',
    'myocyte': 'Muscle cell, derived from mesodermal myoblasts, whose population remains relatively fixed through life and contracts to generate force.',
    'neuroglia': 'Supporting cells of nervous tissue, also called glial cells, that protect neurons, form myelin, and modulate signal propagation.',
    'neuron': 'Excitable cell of nervous tissue that propagates electrochemical impulses called action potentials and releases chemical signals at synapses.',
    'oligodendrocyte': 'Glial cell of the central nervous system that wraps multiple axons in myelin to insulate them and speed conduction.',
    'parenchyma': 'The functional cells of an organ together with its blood vessels and nerves, supported by a stromal framework of connective tissue.',
    'Schwann cell': 'Glial cell of the peripheral nervous system that wraps a single axon segment in myelin to speed nerve impulse conduction.',
    'anchoring junction': 'Strong, flexible connection on lateral or basal surfaces of epithelial cells that mechanically links cells to neighbors or to matrix.',
    'cell junction': 'Specialized intercellular contact between adjacent cell membranes that mechanically connects cells, seals gaps, or allows molecular exchange.',
    'desmosome': 'Patch-like anchoring junction in which cadherin proteins link adjacent cells and tie into intracellular keratin filaments for tensile strength.',
    'hemidesmosomes': 'Half-desmosome anchoring junction that uses integrin proteins to bind the basal surface of an epithelial cell to the basement membrane.',
    'adherens': 'Anchoring junction encircling a cell that uses cadherins or integrins linked to actin filaments to bind adjoining cells together.',
    'gap junction': 'Channel-forming junction creating an intercellular passageway that lets small ions and molecules move directly between adjacent cells.',
    'primary union': 'Healing of a clean wound whose edges are close together, requiring minimal new tissue and producing little scarring.',
    'secondary union': 'Healing of a wound whose edges are widely separated, requiring extensive granulation tissue, wound contraction, and producing larger scars.',
    'tight junction': 'Belt-like junction whose proteins fuse adjacent membranes, sealing the intercellular space and separating apical from basal compartments.',
    'apocrine secretion': 'Mode of exocrine release in which the apical portion of the gland cell pinches off along with the secretory product.',
    'endocrine gland': 'Ductless gland that releases hormones directly into surrounding interstitial fluid and bloodstream rather than through a duct.',
    'exocrine gland': 'Gland that releases its secretions through a duct opening directly or indirectly onto an epithelial surface or external environment.',
    'mucous gland': 'Exocrine gland that secretes a thick, viscous fluid rich in the glycoprotein mucin to lubricate and protect surfaces.',
    'goblet cell': 'Unicellular exocrine gland scattered among epithelial cells that secretes mucus onto the surface of a mucous membrane.',
    'holocrine secretion': 'Mode of exocrine release in which the entire gland cell ruptures and dies, discharging its accumulated product into the duct.',
    'merocrine secretion': 'Most common exocrine secretion mode, in which vesicles release product by exocytosis at the apical surface without damaging the cell.',
    'serous gland': 'Exocrine gland that produces a watery, plasma-like secretion rich in enzymes such as those of salivary or pancreatic origin.',
    'connective tissue membrane': 'Membrane formed solely from connective tissue, such as the synovial membranes of joints or capsules surrounding organs like the kidneys.',
    'cutaneous membrane': 'The skin itself, a stratified squamous keratinized epithelial membrane resting on a layer of connective tissue covering the body surface.',
    'epithelial membrane': 'Membrane composed of an epithelial sheet attached to an underlying layer of connective tissue, such as skin or mucous membranes.',
    'mucous membrane': 'Epithelial membrane that lines body cavities and passageways opening to the exterior, kept moist by mucous secretions.',
    'serous membrane': 'Epithelial membrane of mesothelium plus connective tissue that lines closed ventral cavities and covers their organs, secreting lubricating serous fluid.',
    'synovial membrane': 'Connective tissue membrane lining the cavity of a freely movable joint and secreting synovial fluid that lubricates the joint.',
    'tissue membrane': 'Thin sheet of cells covering or lining a body surface, organ, or cavity, including epithelial and connective tissue types.',
    'clotting': 'Formation of a fibrin protein mesh that traps blood cells, plugs damaged vessels, and binds wound edges together to limit bleeding.',
    'apoptosis': 'Programmed, orderly cell death by which the body destroys cells that are no longer needed or are damaged beyond repair.',
    'atrophy': 'Decrease in the size or mass of a tissue or organ from disuse, aging, or loss of trophic stimulation.',
    'inflammation': 'Standard initial protective response to injury or infection, marked by redness, heat, swelling, and pain that limits damage and starts repair.',
    'histamine': 'Vasoactive chemical released from mast cells during injury that widens blood vessels and increases capillary permeability, driving the inflammatory response.',
    'necrosis': 'Accidental, unprogrammed cell death caused by injury or disease that spills cell contents and triggers an inflammatory response in surrounding tissue.',
    'vasodilation': 'Widening of blood vessels that increases local blood flow, delivering immune cells and nutrients to an injured or active tissue.',
    'wound contraction': 'Process during healing in which the clot and underlying myofibroblasts pull the edges of a wound closer together.',

    // Chapter 5
    'integumentary system': 'Organ system consisting of the skin and accessory structures such as hair, nails, and glands, providing overall body protection.',
    'epidermis': 'Outermost layer of skin, made of keratinized stratified squamous epithelium arranged in four or five cell layers depending on location.',
    'basal cell': 'Cuboidal stem cell of the stratum basale that divides to produce new keratinocytes for the overlying epidermal layers.',
    'dermal papilla': 'Finger-like projection of the dermis extending up into the epidermis that strengthens the junction between the two layers.',
    'dermis': 'Middle skin layer of connective tissue containing blood vessels, nerves, hair follicles, and glands embedded in collagen and elastin.',
    'elastin fibers': 'Stretchy connective-tissue protein fibers in the dermis that give skin its elasticity and ability to recoil after deformation.',
    'eleiden': 'Clear protein derived from keratohyalin that fills cells of the stratum lucidum, giving the layer its translucent appearance in thick skin.',
    'hypodermis': 'Subcutaneous layer beneath the dermis, made of loose connective and adipose tissue, that anchors skin to underlying muscle and bone.',
    'keratin': 'Tough fibrous intracellular protein that gives hair, nails, and the outer skin layers their hardness and water resistance.',
    'keratinocyte': 'Predominant epidermal cell that synthesizes and accumulates keratin as it migrates from the stratum basale toward the skin surface.',
    'keratohyalin': 'Granular protein that accumulates as lamellar granules within keratinocytes of the stratum granulosum and contributes to keratin formation.',
    'Langerhans cell': 'Dendritic immune cell residing in the stratum spinosum that engulfs invading pathogens and presents their antigens to lymphocytes.',
    'Meissner corpuscle': 'Encapsulated tactile receptor in the dermal papillae of the papillary layer that detects light touch on the skin surface.',
    'melanin': 'Brown-to-black pigment produced by melanocytes that colors skin and hair and shields underlying cells from ultraviolet radiation damage.',
    'melanocyte': 'Pigment-producing cell of the stratum basale that synthesizes melanin and transfers it to surrounding keratinocytes via melanosomes.',
    'melanosome': 'Membrane-bound organelle in melanocytes that packages melanin and delivers it to neighboring keratinocytes for skin and hair coloration.',
    'Merkel cell': 'Receptor cell located in the stratum basale that responds to light touch and pressure and signals associated sensory neurons.',
    'Pacinian corpuscle': 'Large, onion-shaped encapsulated receptor in the deep dermis and hypodermis that detects deep pressure and high-frequency vibration.',
    'papillary layer': 'Superficial dermal layer of loose areolar connective tissue containing dermal papillae, capillaries, and tactile receptors.',
    'reticular layer': 'Deeper, thicker dermal layer of dense irregular connective tissue rich in collagen and elastin that gives skin its strength.',
    'stratum basale': 'Deepest epidermal layer of cuboidal cells, including basal stem cells, melanocytes, and Merkel cells, that continuously generates new keratinocytes.',
    'stratum corneum': 'Outermost epidermal layer of dead, flattened, fully keratinized cells that protects underlying tissue and prevents water loss.',
    'stratum granulosum': 'Epidermal layer where flattening keratinocytes accumulate keratohyalin and lamellar granules, beginning the conversion to dead, keratinized cells.',
    'stratum lucidum': 'Thin, translucent epidermal layer of dead cells filled with eleidin, found only in thick skin of the palms and soles.',
    'stratum spinosum': 'Spiny-appearing epidermal layer above the basale where keratinocytes are joined by desmosomes and Langerhans immune cells reside.'
};

// Default slide assignments — many terms can share a slide (multi-label diagrams).
// The matching game treats slides as drop targets that accept multiple terms.
const DEFAULT_SLIDE_ASSIGNMENTS = {
    // ch4_tissue_types — unique micrographs per term
    'cardiac muscle': 'cardiac_intercalated',
    'skeletal muscle': 'skeletal_long',
    'smooth muscle': 'smooth_muscle',
    'striation': 'skeletal_long',
    'nervous tissue': 'neuron_golgi',

    // ch4_neural
    'neuron': 'neuron_golgi',
    'Schwann cell': 'peripheral_nerve',
    'myelin': 'peripheral_nerve',
    'neuroglia': 'neuroglia_cns',
    'astrocyte': 'neuroglia_cns',
    'oligodendrocyte': 'neuroglia_cns',

    // ch4_ct_cells
    'adipocytes': 'adipose_white',
    'chondrocytes': 'hyaline_cartilage_trachea',
    'fibroblast': 'areolar_mesentery',
    'fibrocyte': 'dense_regular_tendon',
    'mesenchymal cell': 'mucous_ct_umbilical',

    // ch4_epithelium — basement membrane components on epithelium diagram
    'apical': 'epithelium_structure',
    'basal lamina': 'epithelium_structure',
    'basement membrane': 'epithelium_structure',
    'reticular lamina': 'epithelium_structure',
    'lamina propria': 'simple_columnar_jejunum',

    // ch4_junctions — all on the OpenStax junctions diagram
    'cell junction': 'cell_junctions',
    'anchoring junction': 'cell_junctions',
    'desmosome': 'cell_junctions',
    'hemidesmosomes': 'cell_junctions',
    'adherens': 'cell_junctions',
    'gap junction': 'cell_junctions',
    'tight junction': 'cell_junctions',

    // ch4_glands — secretion modes on one diagram, others on micrographs
    'apocrine secretion': 'gland_secretion_modes',
    'merocrine secretion': 'gland_secretion_modes',
    'holocrine secretion': 'gland_secretion_modes',
    'goblet cell': 'simple_columnar_jejunum',
    'mucous gland': 'pseudostratified_trachea',
    'serous gland': 'simple_cuboidal_pancreas',

    // ch4_membranes — overview diagram + relevant micrographs
    'cutaneous membrane': 'tissue_membranes',
    'mucous membrane': 'tissue_membranes',
    'serous membrane': 'tissue_membranes',
    'synovial membrane': 'tissue_membranes',
    'epithelial membrane': 'tissue_membranes',
    'connective tissue membrane': 'tissue_membranes',
    'tissue membrane': 'tissue_membranes',

    // ch4_response
    'inflammation': 'inflammation_cascade',
    'histamine': 'inflammation_cascade',
    'vasodilation': 'inflammation_cascade',
    'clotting': 'wound_healing',
    'wound contraction': 'wound_healing',
    'primary union': 'wound_healing',
    'secondary union': 'wound_healing',
    'apoptosis': 'apoptosis_necrosis',
    'necrosis': 'apoptosis_necrosis',

    // ch5_overview
    'integumentary system': 'skin_full_cross_section',
    'epidermis': 'skin_layers',
    'dermis': 'dense_irregular_dermis',
    'hypodermis': 'skin_full_cross_section',
    'dermal papilla': 'skin_layers',
    'papillary layer': 'dense_irregular_dermis',
    'reticular layer': 'dense_irregular_dermis',

    // ch5_strata — all on the skin layers diagram
    'stratum basale': 'skin_layers',
    'stratum spinosum': 'skin_layers',
    'stratum granulosum': 'skin_layers',
    'stratum lucidum': 'skin_layers',
    'stratum corneum': 'skin_layers',

    // ch5_cells — most visible on skin layers diagram
    'basal cell': 'skin_layers',
    'keratinocyte': 'skin_layers',
    'melanocyte': 'skin_layers',
    'Pacinian corpuscle': 'skin_full_cross_section'
    // Langerhans cell, Merkel cell, Meissner corpuscle: no built-in slide; appear in catch-all for upload
};
